export const mockProducts = [
  {
    id: 1,
    name: "Organic Tomatoes",
    description: "Fresh, locally grown organic tomatoes. Perfect for salads and cooking.",
    price: 3.99,
    unit: "kg",
    category: "vegetables",
    inventory: 50,
    farmerId: 1,
    farmName: "Green Valley Farm",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 2,
    name: "Fresh Spinach",
    description: "Nutrient-rich spinach leaves, harvested daily for maximum freshness.",
    price: 2.49,
    unit: "bunch",
    category: "vegetables",
    inventory: 30,
    farmerId: 1,
    farmName: "Green Valley Farm",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 3,
    name: "Bell Peppers",
    description: "Colorful bell peppers, great for stir-fries and salads.",
    price: 4.99,
    unit: "kg",
    category: "vegetables",
    inventory: 40,
    farmerId: 1,
    farmName: "Green Valley Farm",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 4,
    name: "Organic Apples",
    description: "Sweet and crisp apples grown without pesticides.",
    price: 3.49,
    unit: "kg",
    category: "fruits",
    inventory: 75,
    farmerId: 2,
    farmName: "Sunny Orchard",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 5,
    name: "Fresh Strawberries",
    description: "Juicy, ripe strawberries, perfect for desserts or snacking.",
    price: 4.99,
    unit: "500g",
    category: "fruits",
    inventory: 25,
    farmerId: 2,
    farmName: "Sunny Orchard",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 6,
    name: "Organic Milk",
    description: "Fresh, organic whole milk from grass-fed cows.",
    price: 3.99,
    unit: "liter",
    category: "dairy",
    inventory: 20,
    farmerId: 3,
    farmName: "Happy Cow Dairy",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 7,
    name: "Farm Fresh Eggs",
    description: "Free-range eggs from hens raised on organic feed.",
    price: 4.49,
    unit: "dozen",
    category: "dairy",
    inventory: 30,
    farmerId: 3,
    farmName: "Happy Cow Dairy",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 8,
    name: "Carrots",
    description: "Sweet and crunchy carrots, freshly harvested from our farm.",
    price: 1.99,
    unit: "kg",
    category: "vegetables",
    inventory: 60,
    farmerId: 1,
    farmName: "Green Valley Farm",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 9,
    name: "Potatoes",
    description: "Versatile potatoes perfect for roasting, mashing, or frying.",
    price: 2.49,
    unit: "kg",
    category: "vegetables",
    inventory: 80,
    farmerId: 1,
    farmName: "Green Valley Farm",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 10,
    name: "Fresh Basil",
    description: "Aromatic basil leaves, perfect for Italian dishes and pesto.",
    price: 1.99,
    unit: "bunch",
    category: "herbs",
    inventory: 15,
    farmerId: 1,
    farmName: "Green Valley Farm",
    image: "/placeholder.svg?height=200&width=200",
  },
]
